version: 2

references:
  cache-options: &cache-options
    key: package-cache-{{ .Branch }}-{{ .Revision }}
  images: &images
    docker:
      - image: circleci/node:12
      - image: circleci/postgres:9
      - image: redis:4

jobs:
  build:
    <<: *images
    steps:
      - checkout
      - restore_cache:
          <<: *cache-options
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          <<: *cache-options
          paths:
            - ./node_modules

  test:
    <<: *images
    steps:
      - checkout
      - restore_cache:
          <<: *cache-options
      - run:
          name: install postgresql client
          command: sudo apt install -y postgresql-client
      - run:
          name: create test database
          command: createdb "ah_sequelize_test_1" --host localhost --user postgres
      - run:
          name: linter
          command: npm run link
      - run:
          name: test
          command: ./node_modules/.bin/jest --ci

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
